version: '3.8'

services:
  gym-backend:
    build: ./backend/.
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
     app-network:
        aliases:
          - gym-backend

  gym-bot:
    build: ./bot/.
    volumes:
      - ./bot:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    env_file:
      - ./bot/.env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge